
const menu=document.querySelector('.menu');const mobile=document.querySelector('.mobile-menu');if(menu){menu.addEventListener('click',()=>mobile.classList.toggle('open'));mobile.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>mobile.classList.remove('open')))}
const current=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.desktop-nav a,.mobile-menu a').forEach(a=>{const href=a.getAttribute('href');if(href&&href.endsWith(current))a.classList.add('active')});
const reveals=document.querySelectorAll('.reveal');const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.12});reveals.forEach(e=>io.observe(e));
function setupCanvas(id,mode){const c=document.getElementById(id);if(!c)return;const ctx=c.getContext('2d');let w,h,dpr,rx=0,ry=0,mouseX=0,mouseY=0;function size(){const r=c.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);w=r.width;h=r.height;c.width=w*dpr;c.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}size();addEventListener('resize',size);addEventListener('pointermove',e=>{mouseX=(e.clientX/innerWidth-.5)*.7;mouseY=(e.clientY/innerHeight-.5)*.7});
const pts=[];for(let i=0;i<170;i++){let a=Math.random()*Math.PI*2,r=.35+Math.random()*.65;pts.push({a,r,z:Math.random(),s:.5+Math.random()*1.8})}
function draw(){ctx.clearRect(0,0,w,h);rx+=.0025+mouseY*.0005;ry+=.0035+mouseX*.0008;let cx=w/2,cy=h/2,scale=Math.min(w,h)*.34;if(mode==='hero')scale=Math.min(w,h)*.31;ctx.save();ctx.translate(cx,cy);ctx.rotate(Math.sin(ry)*.08);
let glow=ctx.createRadialGradient(0,0,10,0,0,scale*1.4);glow.addColorStop(0,'rgba(100,80,255,.20)');glow.addColorStop(.45,'rgba(205,60,255,.08)');glow.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=glow;ctx.fillRect(-scale*1.5,-scale*1.5,scale*3,scale*3);
const layers=mode==='hero'?5:7;for(let l=0;l<layers;l++){let ang=rx*(l%2?1:-1)+l*.7;ctx.save();ctx.rotate(ang);let ww=scale*(1.1-l*.09),hh=scale*(.23-l*.018);ctx.beginPath();ctx.roundRect(-ww/2,-hh/2,ww,hh,hh*.45);let g=ctx.createLinearGradient(-ww/2,0,ww/2,0);g.addColorStop(0,'rgba(220,65,255,.9)');g.addColorStop(.48,'rgba(89,82,255,.95)');g.addColorStop(1,'rgba(72,205,255,.88)');ctx.fillStyle=g;ctx.shadowBlur=26;ctx.shadowColor='rgba(100,90,255,.4)';ctx.fill();ctx.restore()}
ctx.strokeStyle='rgba(185,178,255,.18)';ctx.lineWidth=1;for(let i=0;i<3;i++){ctx.beginPath();ctx.ellipse(0,0,scale*(1.05+i*.12),scale*(.34+i*.04),rx*.4+i*.7,0,Math.PI*2);ctx.stroke()}
pts.forEach(p=>{let a=p.a+rx*(1+p.z*.3);let x=Math.cos(a)*scale*(.7+p.r*.35);let y=Math.sin(a)*scale*(.24+p.r*.14);let alpha=.15+.65*p.z;ctx.fillStyle=`rgba(210,208,235,${alpha})`;ctx.fillRect(x,y,p.s,p.s)});ctx.restore();requestAnimationFrame(draw)}draw()}
setupCanvas('hero3d','hero');setupCanvas('system3d','system');
const verify=document.getElementById('verifyBtn');if(verify){verify.addEventListener('click',()=>{const s=document.getElementById('demoStatus');s.textContent='Verified onchain. Demo result refreshed locally.';s.style.color='#9de9b2'})}
